"use client"

import { Providers } from "@/app/provider"
import classNames from "classnames"
import type { Metadata } from "next"

import { Inter } from "next/font/google"
import { usePathname } from "next/navigation"

import Navigation from "../Components/TopNavigation/Navigation"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  const authRoutes = ["/auth/signup", "/auth/login"]
  const authRoute = authRoutes.includes(pathname)

  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " " +
          classNames({ "bg-background": !authRoute }) +
          classNames({ "bg-background-auth": authRoute }) +
          " " +
          "bg-cover"
        }
      >
        <Providers>
          {!authRoute && <Navigation />}
          {children}
        </Providers>
      </body>
    </html>
  )
}
